{
 "title": "Llama farm",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Indoors",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "15m" ], "type": "time" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "!=", "value": "Outdoor.1" },
      { "condition": "AND", "key": "name", "operator": "!=", "value": "Garage.1" }
     ]
    }
   ]
  },
  {
   "title": "Garage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "15m" ], "type": "time" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Garage.1" }
     ]
    }
   ]
  },
  {
   "title": "Outdoors",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "15m" ], "type": "time" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Outdoor.1" }
     ]
    }
   ]
  },
  {
   "title": "Relative humidity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "sensors",
     "query": "SELECT \"temperature\" FROM \"sensors\" WHERE $timeFilter GROUP BY \"name\"",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lux",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "lux" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "sensors",
     "query": "SELECT \"temperature\" FROM \"sensors\" WHERE $timeFilter GROUP BY \"name\"",
     "select": [
      [
       { "params": [ "lux" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "sensors",
     "query": "SELECT \"temperature\" FROM \"sensors\" WHERE $timeFilter GROUP BY \"name\"",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Absolute humidity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 7 },
   "yaxes": [
    { "format": "congm3" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "sensors",
     "query": "SELECT (6.112 * POW(2.71828, (17.67 * \"temperature\") / (\"temperature\" + 243.5)) * \"humidity\" * 2.1674) / (273.15 + \"temperature\") FROM \"sensors\" WHERE $timeFilter GROUP BY \"name\"",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 7 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "moving_average(\"battery\")",
     "query": "SELECT moving_average(\"battery\", 10) FROM \"sensors\" WHERE $timeFilter GROUP BY \"name\"",
     "select": [
      [
       { "params": [ "battery" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Indoor Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "sensors",
     "query": "SELECT \"temperature\" FROM \"sensors\" WHERE $timeFilter GROUP BY \"name\"",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "mean" ], "type": "alias" }
      ],
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "max" ], "type": "alias" }
      ],
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "min" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "!=", "value": "Outdoor.1" },
      { "condition": "AND", "key": "name", "operator": "!=", "value": "Garage.1" },
      { "condition": "AND", "key": "name", "operator": "!=", "value": "Fridge.1" }
     ]
    }
   ]
  },
  {
   "title": "Dew point",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 14 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "sensors",
     "query": "SELECT 243.5*(LN(\"humidity\"/100)+((17.67*\"temperature\")/(243.5+\"temperature\")))/(17.67-LN(\"humidity\"/100)-((17.67*\"temperature\")/(243.5+\"temperature\"))) FROM \"sensors\" WHERE $timeFilter GROUP BY \"name\"",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Outdoor temp trend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "outdoor",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "sensors",
     "query": "SELECT MEAN(\"temperature\") FROM \"sensors\" WHERE (\"name\" = 'Outdoor.1') AND $timeFilter GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Outdoor.1" }
     ]
    }
   ]
  }
 ]
}